

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// 沒有可用的模型化描述
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class sendrecordItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// 初始化 sendrecordItem 實體的新執行個體。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sendrecordItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sendrecordItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.sendrecordItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.sendrecordItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendrecordItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendrecordItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// 取得這個應用程式的 Application 物件。Application 物件提供對現用螢幕的存取、開啟螢幕的方法，以及對目前使用者的存取。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// 取得包含資料工作區。資料工作區提供對應用程式中所有資料來源的存取。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int sendRecordID
        {
            get
            {
                return global::LightSwitchApplication.sendrecordItem.DetailsClass.GetValue(this, global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.sendRecordID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendRecordID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendRecordID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendRecordID_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<short> CorpID
        {
            get
            {
                return global::LightSwitchApplication.sendrecordItem.DetailsClass.GetValue(this, global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.CorpID);
            }
            set
            {
                global::LightSwitchApplication.sendrecordItem.DetailsClass.SetValue(this, global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.CorpID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CorpID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CorpID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CorpID_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> sendDate
        {
            get
            {
                return global::LightSwitchApplication.sendrecordItem.DetailsClass.GetValue(this, global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.sendDate);
            }
            set
            {
                global::LightSwitchApplication.sendrecordItem.DetailsClass.SetValue(this, global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.sendDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendDate_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<float> money
        {
            get
            {
                return global::LightSwitchApplication.sendrecordItem.DetailsClass.GetValue(this, global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.money);
            }
            set
            {
                global::LightSwitchApplication.sendrecordItem.DetailsClass.SetValue(this, global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.money, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void money_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void money_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void money_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string sendNum
        {
            get
            {
                return global::LightSwitchApplication.sendrecordItem.DetailsClass.GetValue(this, global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.sendNum);
            }
            set
            {
                global::LightSwitchApplication.sendrecordItem.DetailsClass.SetValue(this, global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.sendNum, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendNum_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendNum_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendNum_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<decimal> weight
        {
            get
            {
                return global::LightSwitchApplication.sendrecordItem.DetailsClass.GetValue(this, global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.weight);
            }
            set
            {
                global::LightSwitchApplication.sendrecordItem.DetailsClass.SetValue(this, global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.weight, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void weight_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void weight_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void weight_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string note
        {
            get
            {
                return global::LightSwitchApplication.sendrecordItem.DetailsClass.GetValue(this, global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.note);
            }
            set
            {
                global::LightSwitchApplication.sendrecordItem.DetailsClass.SetValue(this, global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.note, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void note_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void note_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void note_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public long odID
        {
            get
            {
                return global::LightSwitchApplication.sendrecordItem.DetailsClass.GetValue(this, global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.odID);
            }
            set
            {
                global::LightSwitchApplication.sendrecordItem.DetailsClass.SetValue(this, global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.odID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void odID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void odID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void odID_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.sendtypeItem sendtypeItem
        {
            get
            {
                return global::LightSwitchApplication.sendrecordItem.DetailsClass.GetValue(this, global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.sendtypeItem);
            }
            set
            {
                global::LightSwitchApplication.sendrecordItem.DetailsClass.SetValue(this, global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.sendtypeItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendtypeItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendtypeItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendtypeItem_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.sendrecordItem,
                global::LightSwitchApplication.sendrecordItem.DetailsClass,
                global::LightSwitchApplication.sendrecordItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.sendRecordID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass>.Entry
                __sendrecordItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.sendrecordItem.DetailsClass.__sendrecordItem_CreateNew,
                    global::LightSwitchApplication.sendrecordItem.DetailsClass.__sendrecordItem_Created,
                    global::LightSwitchApplication.sendrecordItem.DetailsClass.__sendrecordItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.sendrecordItem __sendrecordItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.sendrecordItem> es)
            {
                return new global::LightSwitchApplication.sendrecordItem(es);
            }
            private static void __sendrecordItem_Created(global::LightSwitchApplication.sendrecordItem e)
            {
                e.sendrecordItem_Created();
            }
            private static bool __sendrecordItem_AllowSaveWithErrors(global::LightSwitchApplication.sendrecordItem e)
            {
                bool result = false;
                e.sendrecordItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, int> sendRecordID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.sendRecordID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<short>> CorpID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.CorpID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<short>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<global::System.DateTime>> sendDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.sendDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<float>> money
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.money) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<float>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, string> sendNum
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.sendNum) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<decimal>> weight
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.weight) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<decimal>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, string> note
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.note) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, long> odID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.odID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, long>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::LightSwitchApplication.sendtypeItem> sendtypeItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.sendtypeItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::LightSwitchApplication.sendtypeItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int sendRecordID { get; }
                new global::System.Nullable<short> CorpID { get; set; }
                new global::System.Nullable<global::System.DateTime> sendDate { get; set; }
                new global::System.Nullable<float> money { get; set; }
                new string sendNum { get; set; }
                new global::System.Nullable<decimal> weight { get; set; }
                new string note { get; set; }
                new long odID { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation sendtypeItem { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, int>.Entry
                    sendRecordID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, int>.Entry(
                        "sendRecordID",
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendRecordID_Stub,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendRecordID_ComputeIsReadOnly,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendRecordID_Validate,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendRecordID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendRecordID_OnValueChanged);
                private static void _sendRecordID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.sendrecordItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.sendrecordItem.DetailsClass d, object sf)
                {
                    c(d, ref d._sendRecordID, sf);
                }
                private static bool _sendRecordID_ComputeIsReadOnly(global::LightSwitchApplication.sendrecordItem e)
                {
                    bool result = false;
                    e.sendRecordID_IsReadOnly(ref result);
                    return result;
                }
                private static void _sendRecordID_Validate(global::LightSwitchApplication.sendrecordItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.sendRecordID_Validate(r);
                }
                private static int _sendRecordID_GetImplementationValue(global::LightSwitchApplication.sendrecordItem.DetailsClass d)
                {
                    return d.ImplementationEntity.sendRecordID;
                }
                private static void _sendRecordID_OnValueChanged(global::LightSwitchApplication.sendrecordItem e)
                {
                    e.sendRecordID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<short>>.Entry
                    CorpID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<short>>.Entry(
                        "CorpID",
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._CorpID_Stub,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._CorpID_ComputeIsReadOnly,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._CorpID_Validate,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._CorpID_GetImplementationValue,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._CorpID_SetImplementationValue,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._CorpID_OnValueChanged);
                private static void _CorpID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.sendrecordItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<short>>.Data> c, global::LightSwitchApplication.sendrecordItem.DetailsClass d, object sf)
                {
                    c(d, ref d._CorpID, sf);
                }
                private static bool _CorpID_ComputeIsReadOnly(global::LightSwitchApplication.sendrecordItem e)
                {
                    bool result = false;
                    e.CorpID_IsReadOnly(ref result);
                    return result;
                }
                private static void _CorpID_Validate(global::LightSwitchApplication.sendrecordItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CorpID_Validate(r);
                }
                private static global::System.Nullable<short> _CorpID_GetImplementationValue(global::LightSwitchApplication.sendrecordItem.DetailsClass d)
                {
                    return d.ImplementationEntity.CorpID;
                }
                private static void _CorpID_SetImplementationValue(global::LightSwitchApplication.sendrecordItem.DetailsClass d, global::System.Nullable<short> v)
                {
                    d.ImplementationEntity.CorpID = v;
                }
                private static void _CorpID_OnValueChanged(global::LightSwitchApplication.sendrecordItem e)
                {
                    e.CorpID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    sendDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "sendDate",
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendDate_Stub,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendDate_Validate,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendDate_GetImplementationValue,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendDate_SetImplementationValue,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendDate_OnValueChanged);
                private static void _sendDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.sendrecordItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.sendrecordItem.DetailsClass d, object sf)
                {
                    c(d, ref d._sendDate, sf);
                }
                private static bool _sendDate_ComputeIsReadOnly(global::LightSwitchApplication.sendrecordItem e)
                {
                    bool result = false;
                    e.sendDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _sendDate_Validate(global::LightSwitchApplication.sendrecordItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.sendDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _sendDate_GetImplementationValue(global::LightSwitchApplication.sendrecordItem.DetailsClass d)
                {
                    return d.ImplementationEntity.sendDate;
                }
                private static void _sendDate_SetImplementationValue(global::LightSwitchApplication.sendrecordItem.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.sendDate = global::LightSwitchApplication.sendrecordItem.DetailsClass.TruncateDate(v);
                }
                private static void _sendDate_OnValueChanged(global::LightSwitchApplication.sendrecordItem e)
                {
                    e.sendDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<float>>.Entry
                    money = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<float>>.Entry(
                        "money",
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._money_Stub,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._money_ComputeIsReadOnly,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._money_Validate,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._money_GetImplementationValue,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._money_SetImplementationValue,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._money_OnValueChanged);
                private static void _money_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.sendrecordItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<float>>.Data> c, global::LightSwitchApplication.sendrecordItem.DetailsClass d, object sf)
                {
                    c(d, ref d._money, sf);
                }
                private static bool _money_ComputeIsReadOnly(global::LightSwitchApplication.sendrecordItem e)
                {
                    bool result = false;
                    e.money_IsReadOnly(ref result);
                    return result;
                }
                private static void _money_Validate(global::LightSwitchApplication.sendrecordItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.money_Validate(r);
                }
                private static global::System.Nullable<float> _money_GetImplementationValue(global::LightSwitchApplication.sendrecordItem.DetailsClass d)
                {
                    return d.ImplementationEntity.money;
                }
                private static void _money_SetImplementationValue(global::LightSwitchApplication.sendrecordItem.DetailsClass d, global::System.Nullable<float> v)
                {
                    d.ImplementationEntity.money = v;
                }
                private static void _money_OnValueChanged(global::LightSwitchApplication.sendrecordItem e)
                {
                    e.money_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, string>.Entry
                    sendNum = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, string>.Entry(
                        "sendNum",
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendNum_Stub,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendNum_ComputeIsReadOnly,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendNum_Validate,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendNum_GetImplementationValue,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendNum_SetImplementationValue,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendNum_OnValueChanged);
                private static void _sendNum_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.sendrecordItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.sendrecordItem.DetailsClass d, object sf)
                {
                    c(d, ref d._sendNum, sf);
                }
                private static bool _sendNum_ComputeIsReadOnly(global::LightSwitchApplication.sendrecordItem e)
                {
                    bool result = false;
                    e.sendNum_IsReadOnly(ref result);
                    return result;
                }
                private static void _sendNum_Validate(global::LightSwitchApplication.sendrecordItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.sendNum_Validate(r);
                }
                private static string _sendNum_GetImplementationValue(global::LightSwitchApplication.sendrecordItem.DetailsClass d)
                {
                    return d.ImplementationEntity.sendNum;
                }
                private static void _sendNum_SetImplementationValue(global::LightSwitchApplication.sendrecordItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.sendNum = v;
                }
                private static void _sendNum_OnValueChanged(global::LightSwitchApplication.sendrecordItem e)
                {
                    e.sendNum_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<decimal>>.Entry
                    weight = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<decimal>>.Entry(
                        "weight",
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._weight_Stub,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._weight_ComputeIsReadOnly,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._weight_Validate,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._weight_GetImplementationValue,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._weight_SetImplementationValue,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._weight_OnValueChanged);
                private static void _weight_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.sendrecordItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<decimal>>.Data> c, global::LightSwitchApplication.sendrecordItem.DetailsClass d, object sf)
                {
                    c(d, ref d._weight, sf);
                }
                private static bool _weight_ComputeIsReadOnly(global::LightSwitchApplication.sendrecordItem e)
                {
                    bool result = false;
                    e.weight_IsReadOnly(ref result);
                    return result;
                }
                private static void _weight_Validate(global::LightSwitchApplication.sendrecordItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.weight_Validate(r);
                }
                private static global::System.Nullable<decimal> _weight_GetImplementationValue(global::LightSwitchApplication.sendrecordItem.DetailsClass d)
                {
                    return d.ImplementationEntity.weight;
                }
                private static void _weight_SetImplementationValue(global::LightSwitchApplication.sendrecordItem.DetailsClass d, global::System.Nullable<decimal> v)
                {
                    d.ImplementationEntity.weight = v;
                }
                private static void _weight_OnValueChanged(global::LightSwitchApplication.sendrecordItem e)
                {
                    e.weight_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, string>.Entry
                    note = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, string>.Entry(
                        "note",
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._note_Stub,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._note_ComputeIsReadOnly,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._note_Validate,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._note_GetImplementationValue,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._note_SetImplementationValue,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._note_OnValueChanged);
                private static void _note_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.sendrecordItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.sendrecordItem.DetailsClass d, object sf)
                {
                    c(d, ref d._note, sf);
                }
                private static bool _note_ComputeIsReadOnly(global::LightSwitchApplication.sendrecordItem e)
                {
                    bool result = false;
                    e.note_IsReadOnly(ref result);
                    return result;
                }
                private static void _note_Validate(global::LightSwitchApplication.sendrecordItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.note_Validate(r);
                }
                private static string _note_GetImplementationValue(global::LightSwitchApplication.sendrecordItem.DetailsClass d)
                {
                    return d.ImplementationEntity.note;
                }
                private static void _note_SetImplementationValue(global::LightSwitchApplication.sendrecordItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.note = v;
                }
                private static void _note_OnValueChanged(global::LightSwitchApplication.sendrecordItem e)
                {
                    e.note_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, long>.Entry
                    odID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, long>.Entry(
                        "odID",
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._odID_Stub,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._odID_ComputeIsReadOnly,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._odID_Validate,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._odID_GetImplementationValue,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._odID_SetImplementationValue,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._odID_OnValueChanged);
                private static void _odID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.sendrecordItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, long>.Data> c, global::LightSwitchApplication.sendrecordItem.DetailsClass d, object sf)
                {
                    c(d, ref d._odID, sf);
                }
                private static bool _odID_ComputeIsReadOnly(global::LightSwitchApplication.sendrecordItem e)
                {
                    bool result = false;
                    e.odID_IsReadOnly(ref result);
                    return result;
                }
                private static void _odID_Validate(global::LightSwitchApplication.sendrecordItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.odID_Validate(r);
                }
                private static long _odID_GetImplementationValue(global::LightSwitchApplication.sendrecordItem.DetailsClass d)
                {
                    return d.ImplementationEntity.odID;
                }
                private static void _odID_SetImplementationValue(global::LightSwitchApplication.sendrecordItem.DetailsClass d, long v)
                {
                    d.ImplementationEntity.odID = v;
                }
                private static void _odID_OnValueChanged(global::LightSwitchApplication.sendrecordItem e)
                {
                    e.odID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::LightSwitchApplication.sendtypeItem>.Entry
                    sendtypeItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::LightSwitchApplication.sendtypeItem>.Entry(
                        "sendtypeItem",
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendtypeItem_Stub,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendtypeItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendtypeItem_Validate,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendtypeItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendtypeItem_GetImplementationValue,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendtypeItem_SetImplementationValue,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendtypeItem_Refresh,
                        global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties._sendtypeItem_OnValueChanged);
                private static void _sendtypeItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.sendrecordItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::LightSwitchApplication.sendtypeItem>.Data> c, global::LightSwitchApplication.sendrecordItem.DetailsClass d, object sf)
                {
                    c(d, ref d._sendtypeItem, sf);
                }
                private static bool _sendtypeItem_ComputeIsReadOnly(global::LightSwitchApplication.sendrecordItem e)
                {
                    bool result = false;
                    e.sendtypeItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _sendtypeItem_Validate(global::LightSwitchApplication.sendrecordItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.sendtypeItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _sendtypeItem_GetCoreImplementationValue(global::LightSwitchApplication.sendrecordItem.DetailsClass d)
                {
                    return d.ImplementationEntity.sendtypeItem;
                }
                private static global::LightSwitchApplication.sendtypeItem _sendtypeItem_GetImplementationValue(global::LightSwitchApplication.sendrecordItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass>(global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.sendtypeItem, ref d._sendtypeItem);
                }
                private static void _sendtypeItem_SetImplementationValue(global::LightSwitchApplication.sendrecordItem.DetailsClass d, global::LightSwitchApplication.sendtypeItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.sendtypeItem, ref d._sendtypeItem, (i, ev) => i.sendtypeItem = ev, v);
                }
                private static void _sendtypeItem_Refresh(global::LightSwitchApplication.sendrecordItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.sendrecordItem.DetailsClass.PropertySetProperties.sendtypeItem, ref d._sendtypeItem);
                }
                private static void _sendtypeItem_OnValueChanged(global::LightSwitchApplication.sendrecordItem e)
                {
                    e.sendtypeItem_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, int>.Data _sendRecordID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<short>>.Data _CorpID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _sendDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<float>>.Data _money;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, string>.Data _sendNum;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::System.Nullable<decimal>>.Data _weight;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, string>.Data _note;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, long>.Data _odID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass, global::LightSwitchApplication.sendtypeItem>.Data _sendtypeItem;
            
        }
    
        #endregion
    }
    
    #endregion
}
