

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// 沒有可用的模型化描述
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class eorderitemItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// 初始化 eorderitemItem 實體的新執行個體。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public eorderitemItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public eorderitemItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.eorderitemItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.eorderitemItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void eorderitemItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void eorderitemItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// 取得這個應用程式的 Application 物件。Application 物件提供對現用螢幕的存取、開啟螢幕的方法，以及對目前使用者的存取。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// 取得包含資料工作區。資料工作區提供對應用程式中所有資料來源的存取。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public long odItemID
        {
            get
            {
                return global::LightSwitchApplication.eorderitemItem.DetailsClass.GetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.odItemID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void odItemID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void odItemID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void odItemID_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<long> invi
        {
            get
            {
                return global::LightSwitchApplication.eorderitemItem.DetailsClass.GetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.invi);
            }
            set
            {
                global::LightSwitchApplication.eorderitemItem.DetailsClass.SetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.invi, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void invi_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void invi_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void invi_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string disCount
        {
            get
            {
                return global::LightSwitchApplication.eorderitemItem.DetailsClass.GetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.disCount);
            }
            set
            {
                global::LightSwitchApplication.eorderitemItem.DetailsClass.SetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.disCount, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void disCount_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void disCount_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void disCount_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<double> qty
        {
            get
            {
                return global::LightSwitchApplication.eorderitemItem.DetailsClass.GetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.qty);
            }
            set
            {
                global::LightSwitchApplication.eorderitemItem.DetailsClass.SetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.qty, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void qty_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void qty_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void qty_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string iunitDesc
        {
            get
            {
                return global::LightSwitchApplication.eorderitemItem.DetailsClass.GetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.iunitDesc);
            }
            set
            {
                global::LightSwitchApplication.eorderitemItem.DetailsClass.SetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.iunitDesc, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void iunitDesc_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void iunitDesc_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void iunitDesc_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<double> unitPrice
        {
            get
            {
                return global::LightSwitchApplication.eorderitemItem.DetailsClass.GetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.unitPrice);
            }
            set
            {
                global::LightSwitchApplication.eorderitemItem.DetailsClass.SetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.unitPrice, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void unitPrice_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void unitPrice_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void unitPrice_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string isValue
        {
            get
            {
                return global::LightSwitchApplication.eorderitemItem.DetailsClass.GetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.isValue);
            }
            set
            {
                global::LightSwitchApplication.eorderitemItem.DetailsClass.SetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.isValue, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void isValue_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void isValue_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void isValue_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<long> oldItemPrID
        {
            get
            {
                return global::LightSwitchApplication.eorderitemItem.DetailsClass.GetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.oldItemPrID);
            }
            set
            {
                global::LightSwitchApplication.eorderitemItem.DetailsClass.SetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.oldItemPrID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void oldItemPrID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void oldItemPrID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void oldItemPrID_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> deliveryDate
        {
            get
            {
                return global::LightSwitchApplication.eorderitemItem.DetailsClass.GetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.deliveryDate);
            }
            set
            {
                global::LightSwitchApplication.eorderitemItem.DetailsClass.SetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.deliveryDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void deliveryDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void deliveryDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void deliveryDate_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string note
        {
            get
            {
                return global::LightSwitchApplication.eorderitemItem.DetailsClass.GetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.note);
            }
            set
            {
                global::LightSwitchApplication.eorderitemItem.DetailsClass.SetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.note, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void note_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void note_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void note_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ProdDesc
        {
            get
            {
                return global::LightSwitchApplication.eorderitemItem.DetailsClass.GetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.ProdDesc);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProdDesc_Compute(ref string result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProdDesc_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int SubTotal
        {
            get
            {
                return global::LightSwitchApplication.eorderitemItem.DetailsClass.GetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.SubTotal);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubTotal_Compute(ref int result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SubTotal_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> isPrint
        {
            get
            {
                return global::LightSwitchApplication.eorderitemItem.DetailsClass.GetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.isPrint);
            }
            set
            {
                global::LightSwitchApplication.eorderitemItem.DetailsClass.SetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.isPrint, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void isPrint_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void isPrint_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void isPrint_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.eorderItem eorderItem1
        {
            get
            {
                return global::LightSwitchApplication.eorderitemItem.DetailsClass.GetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.eorderItem1);
            }
            set
            {
                global::LightSwitchApplication.eorderitemItem.DetailsClass.SetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.eorderItem1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void eorderItem1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void eorderItem1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void eorderItem1_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.productcodeItem productcodeItem
        {
            get
            {
                return global::LightSwitchApplication.eorderitemItem.DetailsClass.GetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.productcodeItem);
            }
            set
            {
                global::LightSwitchApplication.eorderitemItem.DetailsClass.SetValue(this, global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.productcodeItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void productcodeItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void productcodeItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void productcodeItem_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.eorderitemItem,
                global::LightSwitchApplication.eorderitemItem.DetailsClass,
                global::LightSwitchApplication.eorderitemItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.odItemID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass>.Entry
                __eorderitemItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.eorderitemItem.DetailsClass.__eorderitemItem_CreateNew,
                    global::LightSwitchApplication.eorderitemItem.DetailsClass.__eorderitemItem_Created,
                    global::LightSwitchApplication.eorderitemItem.DetailsClass.__eorderitemItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.eorderitemItem __eorderitemItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.eorderitemItem> es)
            {
                return new global::LightSwitchApplication.eorderitemItem(es);
            }
            private static void __eorderitemItem_Created(global::LightSwitchApplication.eorderitemItem e)
            {
                e.eorderitemItem_Created();
            }
            private static bool __eorderitemItem_AllowSaveWithErrors(global::LightSwitchApplication.eorderitemItem e)
            {
                bool result = false;
                e.eorderitemItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, long> odItemID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.odItemID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, long>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<long>> invi
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.invi) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<long>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string> disCount
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.disCount) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<double>> qty
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.qty) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<double>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string> iunitDesc
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.iunitDesc) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<double>> unitPrice
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.unitPrice) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<double>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string> isValue
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.isValue) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<long>> oldItemPrID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.oldItemPrID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<long>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<global::System.DateTime>> deliveryDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.deliveryDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string> note
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.note) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string> ProdDesc
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.ProdDesc) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, int> SubTotal
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.SubTotal) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<bool>> isPrint
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.isPrint) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::LightSwitchApplication.eorderItem> eorderItem1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.eorderItem1) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::LightSwitchApplication.eorderItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::LightSwitchApplication.productcodeItem> productcodeItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.productcodeItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::LightSwitchApplication.productcodeItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new long odItemID { get; }
                new global::System.Nullable<long> invi { get; set; }
                new string disCount { get; set; }
                new global::System.Nullable<double> qty { get; set; }
                new string iunitDesc { get; set; }
                new global::System.Nullable<double> unitPrice { get; set; }
                new string isValue { get; set; }
                new global::System.Nullable<long> oldItemPrID { get; set; }
                new global::System.Nullable<global::System.DateTime> deliveryDate { get; set; }
                new string note { get; set; }
                new global::System.Nullable<bool> isPrint { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation eorderItem1 { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation productcodeItem { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, long>.Entry
                    odItemID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, long>.Entry(
                        "odItemID",
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._odItemID_Stub,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._odItemID_ComputeIsReadOnly,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._odItemID_Validate,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._odItemID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._odItemID_OnValueChanged);
                private static void _odItemID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.eorderitemItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, long>.Data> c, global::LightSwitchApplication.eorderitemItem.DetailsClass d, object sf)
                {
                    c(d, ref d._odItemID, sf);
                }
                private static bool _odItemID_ComputeIsReadOnly(global::LightSwitchApplication.eorderitemItem e)
                {
                    bool result = false;
                    e.odItemID_IsReadOnly(ref result);
                    return result;
                }
                private static void _odItemID_Validate(global::LightSwitchApplication.eorderitemItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.odItemID_Validate(r);
                }
                private static long _odItemID_GetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d)
                {
                    return d.ImplementationEntity.odItemID;
                }
                private static void _odItemID_OnValueChanged(global::LightSwitchApplication.eorderitemItem e)
                {
                    e.odItemID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<long>>.Entry
                    invi = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<long>>.Entry(
                        "invi",
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._invi_Stub,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._invi_ComputeIsReadOnly,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._invi_Validate,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._invi_GetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._invi_SetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._invi_OnValueChanged);
                private static void _invi_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.eorderitemItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<long>>.Data> c, global::LightSwitchApplication.eorderitemItem.DetailsClass d, object sf)
                {
                    c(d, ref d._invi, sf);
                }
                private static bool _invi_ComputeIsReadOnly(global::LightSwitchApplication.eorderitemItem e)
                {
                    bool result = false;
                    e.invi_IsReadOnly(ref result);
                    return result;
                }
                private static void _invi_Validate(global::LightSwitchApplication.eorderitemItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.invi_Validate(r);
                }
                private static global::System.Nullable<long> _invi_GetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d)
                {
                    return d.ImplementationEntity.invi;
                }
                private static void _invi_SetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d, global::System.Nullable<long> v)
                {
                    d.ImplementationEntity.invi = v;
                }
                private static void _invi_OnValueChanged(global::LightSwitchApplication.eorderitemItem e)
                {
                    e.invi_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>.Entry
                    disCount = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>.Entry(
                        "disCount",
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._disCount_Stub,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._disCount_ComputeIsReadOnly,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._disCount_Validate,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._disCount_GetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._disCount_SetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._disCount_OnValueChanged);
                private static void _disCount_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.eorderitemItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.eorderitemItem.DetailsClass d, object sf)
                {
                    c(d, ref d._disCount, sf);
                }
                private static bool _disCount_ComputeIsReadOnly(global::LightSwitchApplication.eorderitemItem e)
                {
                    bool result = false;
                    e.disCount_IsReadOnly(ref result);
                    return result;
                }
                private static void _disCount_Validate(global::LightSwitchApplication.eorderitemItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.disCount_Validate(r);
                }
                private static string _disCount_GetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d)
                {
                    return d.ImplementationEntity.disCount;
                }
                private static void _disCount_SetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.disCount = v;
                }
                private static void _disCount_OnValueChanged(global::LightSwitchApplication.eorderitemItem e)
                {
                    e.disCount_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<double>>.Entry
                    qty = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<double>>.Entry(
                        "qty",
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._qty_Stub,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._qty_ComputeIsReadOnly,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._qty_Validate,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._qty_GetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._qty_SetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._qty_OnValueChanged);
                private static void _qty_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.eorderitemItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<double>>.Data> c, global::LightSwitchApplication.eorderitemItem.DetailsClass d, object sf)
                {
                    c(d, ref d._qty, sf);
                }
                private static bool _qty_ComputeIsReadOnly(global::LightSwitchApplication.eorderitemItem e)
                {
                    bool result = false;
                    e.qty_IsReadOnly(ref result);
                    return result;
                }
                private static void _qty_Validate(global::LightSwitchApplication.eorderitemItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.qty_Validate(r);
                }
                private static global::System.Nullable<double> _qty_GetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d)
                {
                    return d.ImplementationEntity.qty;
                }
                private static void _qty_SetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d, global::System.Nullable<double> v)
                {
                    d.ImplementationEntity.qty = v;
                }
                private static void _qty_OnValueChanged(global::LightSwitchApplication.eorderitemItem e)
                {
                    e.qty_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>.Entry
                    iunitDesc = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>.Entry(
                        "iunitDesc",
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._iunitDesc_Stub,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._iunitDesc_ComputeIsReadOnly,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._iunitDesc_Validate,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._iunitDesc_GetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._iunitDesc_SetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._iunitDesc_OnValueChanged);
                private static void _iunitDesc_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.eorderitemItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.eorderitemItem.DetailsClass d, object sf)
                {
                    c(d, ref d._iunitDesc, sf);
                }
                private static bool _iunitDesc_ComputeIsReadOnly(global::LightSwitchApplication.eorderitemItem e)
                {
                    bool result = false;
                    e.iunitDesc_IsReadOnly(ref result);
                    return result;
                }
                private static void _iunitDesc_Validate(global::LightSwitchApplication.eorderitemItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.iunitDesc_Validate(r);
                }
                private static string _iunitDesc_GetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d)
                {
                    return d.ImplementationEntity.iunitDesc;
                }
                private static void _iunitDesc_SetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.iunitDesc = v;
                }
                private static void _iunitDesc_OnValueChanged(global::LightSwitchApplication.eorderitemItem e)
                {
                    e.iunitDesc_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<double>>.Entry
                    unitPrice = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<double>>.Entry(
                        "unitPrice",
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._unitPrice_Stub,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._unitPrice_ComputeIsReadOnly,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._unitPrice_Validate,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._unitPrice_GetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._unitPrice_SetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._unitPrice_OnValueChanged);
                private static void _unitPrice_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.eorderitemItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<double>>.Data> c, global::LightSwitchApplication.eorderitemItem.DetailsClass d, object sf)
                {
                    c(d, ref d._unitPrice, sf);
                }
                private static bool _unitPrice_ComputeIsReadOnly(global::LightSwitchApplication.eorderitemItem e)
                {
                    bool result = false;
                    e.unitPrice_IsReadOnly(ref result);
                    return result;
                }
                private static void _unitPrice_Validate(global::LightSwitchApplication.eorderitemItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.unitPrice_Validate(r);
                }
                private static global::System.Nullable<double> _unitPrice_GetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d)
                {
                    return d.ImplementationEntity.unitPrice;
                }
                private static void _unitPrice_SetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d, global::System.Nullable<double> v)
                {
                    d.ImplementationEntity.unitPrice = v;
                }
                private static void _unitPrice_OnValueChanged(global::LightSwitchApplication.eorderitemItem e)
                {
                    e.unitPrice_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>.Entry
                    isValue = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>.Entry(
                        "isValue",
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._isValue_Stub,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._isValue_ComputeIsReadOnly,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._isValue_Validate,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._isValue_GetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._isValue_SetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._isValue_OnValueChanged);
                private static void _isValue_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.eorderitemItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.eorderitemItem.DetailsClass d, object sf)
                {
                    c(d, ref d._isValue, sf);
                }
                private static bool _isValue_ComputeIsReadOnly(global::LightSwitchApplication.eorderitemItem e)
                {
                    bool result = false;
                    e.isValue_IsReadOnly(ref result);
                    return result;
                }
                private static void _isValue_Validate(global::LightSwitchApplication.eorderitemItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.isValue_Validate(r);
                }
                private static string _isValue_GetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d)
                {
                    return d.ImplementationEntity.isValue;
                }
                private static void _isValue_SetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.isValue = v;
                }
                private static void _isValue_OnValueChanged(global::LightSwitchApplication.eorderitemItem e)
                {
                    e.isValue_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<long>>.Entry
                    oldItemPrID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<long>>.Entry(
                        "oldItemPrID",
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._oldItemPrID_Stub,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._oldItemPrID_ComputeIsReadOnly,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._oldItemPrID_Validate,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._oldItemPrID_GetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._oldItemPrID_SetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._oldItemPrID_OnValueChanged);
                private static void _oldItemPrID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.eorderitemItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<long>>.Data> c, global::LightSwitchApplication.eorderitemItem.DetailsClass d, object sf)
                {
                    c(d, ref d._oldItemPrID, sf);
                }
                private static bool _oldItemPrID_ComputeIsReadOnly(global::LightSwitchApplication.eorderitemItem e)
                {
                    bool result = false;
                    e.oldItemPrID_IsReadOnly(ref result);
                    return result;
                }
                private static void _oldItemPrID_Validate(global::LightSwitchApplication.eorderitemItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.oldItemPrID_Validate(r);
                }
                private static global::System.Nullable<long> _oldItemPrID_GetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d)
                {
                    return d.ImplementationEntity.oldItemPrID;
                }
                private static void _oldItemPrID_SetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d, global::System.Nullable<long> v)
                {
                    d.ImplementationEntity.oldItemPrID = v;
                }
                private static void _oldItemPrID_OnValueChanged(global::LightSwitchApplication.eorderitemItem e)
                {
                    e.oldItemPrID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    deliveryDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "deliveryDate",
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._deliveryDate_Stub,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._deliveryDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._deliveryDate_Validate,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._deliveryDate_GetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._deliveryDate_SetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._deliveryDate_OnValueChanged);
                private static void _deliveryDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.eorderitemItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.eorderitemItem.DetailsClass d, object sf)
                {
                    c(d, ref d._deliveryDate, sf);
                }
                private static bool _deliveryDate_ComputeIsReadOnly(global::LightSwitchApplication.eorderitemItem e)
                {
                    bool result = false;
                    e.deliveryDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _deliveryDate_Validate(global::LightSwitchApplication.eorderitemItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.deliveryDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _deliveryDate_GetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d)
                {
                    return d.ImplementationEntity.deliveryDate;
                }
                private static void _deliveryDate_SetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.deliveryDate = global::LightSwitchApplication.eorderitemItem.DetailsClass.TruncateDate(v);
                }
                private static void _deliveryDate_OnValueChanged(global::LightSwitchApplication.eorderitemItem e)
                {
                    e.deliveryDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>.Entry
                    note = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>.Entry(
                        "note",
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._note_Stub,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._note_ComputeIsReadOnly,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._note_Validate,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._note_GetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._note_SetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._note_OnValueChanged);
                private static void _note_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.eorderitemItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.eorderitemItem.DetailsClass d, object sf)
                {
                    c(d, ref d._note, sf);
                }
                private static bool _note_ComputeIsReadOnly(global::LightSwitchApplication.eorderitemItem e)
                {
                    bool result = false;
                    e.note_IsReadOnly(ref result);
                    return result;
                }
                private static void _note_Validate(global::LightSwitchApplication.eorderitemItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.note_Validate(r);
                }
                private static string _note_GetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d)
                {
                    return d.ImplementationEntity.note;
                }
                private static void _note_SetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.note = v;
                }
                private static void _note_OnValueChanged(global::LightSwitchApplication.eorderitemItem e)
                {
                    e.note_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>.Entry
                    ProdDesc = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>.Entry(
                        "ProdDesc",
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._ProdDesc_Stub,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._ProdDesc_Validate,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._ProdDesc_ComputeValue);
                private static void _ProdDesc_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.eorderitemItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.eorderitemItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ProdDesc, sf);
                }
                private static void _ProdDesc_Validate(global::LightSwitchApplication.eorderitemItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ProdDesc_Validate(r);
                }
                private static string _ProdDesc_ComputeValue(global::LightSwitchApplication.eorderitemItem e)
                {
                    string value = default(string);
                    e.ProdDesc_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, int>.Entry
                    SubTotal = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, int>.Entry(
                        "SubTotal",
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._SubTotal_Stub,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._SubTotal_Validate,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._SubTotal_ComputeValue);
                private static void _SubTotal_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.eorderitemItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.eorderitemItem.DetailsClass d, object sf)
                {
                    c(d, ref d._SubTotal, sf);
                }
                private static void _SubTotal_Validate(global::LightSwitchApplication.eorderitemItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SubTotal_Validate(r);
                }
                private static int _SubTotal_ComputeValue(global::LightSwitchApplication.eorderitemItem e)
                {
                    int value = default(int);
                    e.SubTotal_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<bool>>.Entry
                    isPrint = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "isPrint",
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._isPrint_Stub,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._isPrint_ComputeIsReadOnly,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._isPrint_Validate,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._isPrint_GetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._isPrint_SetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._isPrint_OnValueChanged);
                private static void _isPrint_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.eorderitemItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.eorderitemItem.DetailsClass d, object sf)
                {
                    c(d, ref d._isPrint, sf);
                }
                private static bool _isPrint_ComputeIsReadOnly(global::LightSwitchApplication.eorderitemItem e)
                {
                    bool result = false;
                    e.isPrint_IsReadOnly(ref result);
                    return result;
                }
                private static void _isPrint_Validate(global::LightSwitchApplication.eorderitemItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.isPrint_Validate(r);
                }
                private static global::System.Nullable<bool> _isPrint_GetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d)
                {
                    return d.ImplementationEntity.isPrint;
                }
                private static void _isPrint_SetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.isPrint = v;
                }
                private static void _isPrint_OnValueChanged(global::LightSwitchApplication.eorderitemItem e)
                {
                    e.isPrint_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::LightSwitchApplication.eorderItem>.Entry
                    eorderItem1 = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::LightSwitchApplication.eorderItem>.Entry(
                        "eorderItem1",
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._eorderItem1_Stub,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._eorderItem1_ComputeIsReadOnly,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._eorderItem1_Validate,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._eorderItem1_GetCoreImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._eorderItem1_GetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._eorderItem1_SetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._eorderItem1_Refresh,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._eorderItem1_OnValueChanged);
                private static void _eorderItem1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.eorderitemItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::LightSwitchApplication.eorderItem>.Data> c, global::LightSwitchApplication.eorderitemItem.DetailsClass d, object sf)
                {
                    c(d, ref d._eorderItem1, sf);
                }
                private static bool _eorderItem1_ComputeIsReadOnly(global::LightSwitchApplication.eorderitemItem e)
                {
                    bool result = false;
                    e.eorderItem1_IsReadOnly(ref result);
                    return result;
                }
                private static void _eorderItem1_Validate(global::LightSwitchApplication.eorderitemItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.eorderItem1_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _eorderItem1_GetCoreImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d)
                {
                    return d.ImplementationEntity.eorderItem1;
                }
                private static global::LightSwitchApplication.eorderItem _eorderItem1_GetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.eorderItem, global::LightSwitchApplication.eorderItem.DetailsClass>(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.eorderItem1, ref d._eorderItem1);
                }
                private static void _eorderItem1_SetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d, global::LightSwitchApplication.eorderItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.eorderItem1, ref d._eorderItem1, (i, ev) => i.eorderItem1 = ev, v);
                }
                private static void _eorderItem1_Refresh(global::LightSwitchApplication.eorderitemItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.eorderItem1, ref d._eorderItem1);
                }
                private static void _eorderItem1_OnValueChanged(global::LightSwitchApplication.eorderitemItem e)
                {
                    e.eorderItem1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::LightSwitchApplication.productcodeItem>.Entry
                    productcodeItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::LightSwitchApplication.productcodeItem>.Entry(
                        "productcodeItem",
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._productcodeItem_Stub,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._productcodeItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._productcodeItem_Validate,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._productcodeItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._productcodeItem_GetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._productcodeItem_SetImplementationValue,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._productcodeItem_Refresh,
                        global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties._productcodeItem_OnValueChanged);
                private static void _productcodeItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.eorderitemItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::LightSwitchApplication.productcodeItem>.Data> c, global::LightSwitchApplication.eorderitemItem.DetailsClass d, object sf)
                {
                    c(d, ref d._productcodeItem, sf);
                }
                private static bool _productcodeItem_ComputeIsReadOnly(global::LightSwitchApplication.eorderitemItem e)
                {
                    bool result = false;
                    e.productcodeItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _productcodeItem_Validate(global::LightSwitchApplication.eorderitemItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.productcodeItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _productcodeItem_GetCoreImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d)
                {
                    return d.ImplementationEntity.productcodeItem;
                }
                private static global::LightSwitchApplication.productcodeItem _productcodeItem_GetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.productcodeItem, global::LightSwitchApplication.productcodeItem.DetailsClass>(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.productcodeItem, ref d._productcodeItem);
                }
                private static void _productcodeItem_SetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass d, global::LightSwitchApplication.productcodeItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.productcodeItem, ref d._productcodeItem, (i, ev) => i.productcodeItem = ev, v);
                }
                private static void _productcodeItem_Refresh(global::LightSwitchApplication.eorderitemItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.eorderitemItem.DetailsClass.PropertySetProperties.productcodeItem, ref d._productcodeItem);
                }
                private static void _productcodeItem_OnValueChanged(global::LightSwitchApplication.eorderitemItem e)
                {
                    e.productcodeItem_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, long>.Data _odItemID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<long>>.Data _invi;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>.Data _disCount;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<double>>.Data _qty;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>.Data _iunitDesc;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<double>>.Data _unitPrice;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>.Data _isValue;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<long>>.Data _oldItemPrID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _deliveryDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>.Data _note;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, string>.Data _ProdDesc;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, int>.Data _SubTotal;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::System.Nullable<bool>>.Data _isPrint;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::LightSwitchApplication.eorderItem>.Data _eorderItem1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.eorderitemItem, global::LightSwitchApplication.eorderitemItem.DetailsClass, global::LightSwitchApplication.productcodeItem>.Data _productcodeItem;
            
        }
    
        #endregion
    }
    
    #endregion
}
