

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// 沒有可用的模型化描述
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class employeecodeItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// 初始化 employeecodeItem 實體的新執行個體。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public employeecodeItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public employeecodeItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.employeecodeItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.employeecodeItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void employeecodeItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void employeecodeItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// 取得這個應用程式的 Application 物件。Application 物件提供對現用螢幕的存取、開啟螢幕的方法，以及對目前使用者的存取。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// 取得包含資料工作區。資料工作區提供對應用程式中所有資料來源的存取。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int empID
        {
            get
            {
                return global::LightSwitchApplication.employeecodeItem.DetailsClass.GetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empID_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string empAcc
        {
            get
            {
                return global::LightSwitchApplication.employeecodeItem.DetailsClass.GetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empAcc);
            }
            set
            {
                global::LightSwitchApplication.employeecodeItem.DetailsClass.SetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empAcc, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empAcc_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empAcc_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empAcc_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<short> empsellStoreID
        {
            get
            {
                return global::LightSwitchApplication.employeecodeItem.DetailsClass.GetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empsellStoreID);
            }
            set
            {
                global::LightSwitchApplication.employeecodeItem.DetailsClass.SetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empsellStoreID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empsellStoreID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empsellStoreID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empsellStoreID_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string empCode
        {
            get
            {
                return global::LightSwitchApplication.employeecodeItem.DetailsClass.GetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empCode);
            }
            set
            {
                global::LightSwitchApplication.employeecodeItem.DetailsClass.SetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empCode, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empCode_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empCode_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empCode_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string empPws
        {
            get
            {
                return global::LightSwitchApplication.employeecodeItem.DetailsClass.GetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empPws);
            }
            set
            {
                global::LightSwitchApplication.employeecodeItem.DetailsClass.SetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empPws, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empPws_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empPws_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empPws_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string empName
        {
            get
            {
                return global::LightSwitchApplication.employeecodeItem.DetailsClass.GetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empName);
            }
            set
            {
                global::LightSwitchApplication.employeecodeItem.DetailsClass.SetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empName_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string empTel
        {
            get
            {
                return global::LightSwitchApplication.employeecodeItem.DetailsClass.GetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empTel);
            }
            set
            {
                global::LightSwitchApplication.employeecodeItem.DetailsClass.SetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empTel, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empTel_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empTel_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empTel_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string empMobile
        {
            get
            {
                return global::LightSwitchApplication.employeecodeItem.DetailsClass.GetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empMobile);
            }
            set
            {
                global::LightSwitchApplication.employeecodeItem.DetailsClass.SetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empMobile, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empMobile_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empMobile_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empMobile_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string empAdd
        {
            get
            {
                return global::LightSwitchApplication.employeecodeItem.DetailsClass.GetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empAdd);
            }
            set
            {
                global::LightSwitchApplication.employeecodeItem.DetailsClass.SetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empAdd, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empAdd_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empAdd_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empAdd_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<short> empDepar
        {
            get
            {
                return global::LightSwitchApplication.employeecodeItem.DetailsClass.GetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empDepar);
            }
            set
            {
                global::LightSwitchApplication.employeecodeItem.DetailsClass.SetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empDepar, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empDepar_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empDepar_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empDepar_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string isAdmin
        {
            get
            {
                return global::LightSwitchApplication.employeecodeItem.DetailsClass.GetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.isAdmin);
            }
            set
            {
                global::LightSwitchApplication.employeecodeItem.DetailsClass.SetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.isAdmin, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void isAdmin_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void isAdmin_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void isAdmin_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string empEmail
        {
            get
            {
                return global::LightSwitchApplication.employeecodeItem.DetailsClass.GetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empEmail);
            }
            set
            {
                global::LightSwitchApplication.employeecodeItem.DetailsClass.SetValue(this, global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empEmail, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empEmail_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empEmail_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void empEmail_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.employeecodeItem,
                global::LightSwitchApplication.employeecodeItem.DetailsClass,
                global::LightSwitchApplication.employeecodeItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass>.Entry
                __employeecodeItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.employeecodeItem.DetailsClass.__employeecodeItem_CreateNew,
                    global::LightSwitchApplication.employeecodeItem.DetailsClass.__employeecodeItem_Created,
                    global::LightSwitchApplication.employeecodeItem.DetailsClass.__employeecodeItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.employeecodeItem __employeecodeItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.employeecodeItem> es)
            {
                return new global::LightSwitchApplication.employeecodeItem(es);
            }
            private static void __employeecodeItem_Created(global::LightSwitchApplication.employeecodeItem e)
            {
                e.employeecodeItem_Created();
            }
            private static bool __employeecodeItem_AllowSaveWithErrors(global::LightSwitchApplication.employeecodeItem e)
            {
                bool result = false;
                e.employeecodeItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, int> empID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string> empAcc
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empAcc) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, global::System.Nullable<short>> empsellStoreID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empsellStoreID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, global::System.Nullable<short>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string> empCode
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empCode) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string> empPws
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empPws) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string> empName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string> empTel
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empTel) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string> empMobile
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empMobile) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string> empAdd
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empAdd) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, global::System.Nullable<short>> empDepar
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empDepar) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, global::System.Nullable<short>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string> isAdmin
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.isAdmin) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string> empEmail
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties.empEmail) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int empID { get; }
                new string empAcc { get; set; }
                new global::System.Nullable<short> empsellStoreID { get; set; }
                new string empCode { get; set; }
                new string empPws { get; set; }
                new string empName { get; set; }
                new string empTel { get; set; }
                new string empMobile { get; set; }
                new string empAdd { get; set; }
                new global::System.Nullable<short> empDepar { get; set; }
                new string isAdmin { get; set; }
                new string empEmail { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, int>.Entry
                    empID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, int>.Entry(
                        "empID",
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empID_Stub,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empID_ComputeIsReadOnly,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empID_Validate,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empID_OnValueChanged);
                private static void _empID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.employeecodeItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.employeecodeItem.DetailsClass d, object sf)
                {
                    c(d, ref d._empID, sf);
                }
                private static bool _empID_ComputeIsReadOnly(global::LightSwitchApplication.employeecodeItem e)
                {
                    bool result = false;
                    e.empID_IsReadOnly(ref result);
                    return result;
                }
                private static void _empID_Validate(global::LightSwitchApplication.employeecodeItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.empID_Validate(r);
                }
                private static int _empID_GetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d)
                {
                    return d.ImplementationEntity.empID;
                }
                private static void _empID_OnValueChanged(global::LightSwitchApplication.employeecodeItem e)
                {
                    e.empID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Entry
                    empAcc = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Entry(
                        "empAcc",
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empAcc_Stub,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empAcc_ComputeIsReadOnly,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empAcc_Validate,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empAcc_GetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empAcc_SetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empAcc_OnValueChanged);
                private static void _empAcc_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.employeecodeItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.employeecodeItem.DetailsClass d, object sf)
                {
                    c(d, ref d._empAcc, sf);
                }
                private static bool _empAcc_ComputeIsReadOnly(global::LightSwitchApplication.employeecodeItem e)
                {
                    bool result = false;
                    e.empAcc_IsReadOnly(ref result);
                    return result;
                }
                private static void _empAcc_Validate(global::LightSwitchApplication.employeecodeItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.empAcc_Validate(r);
                }
                private static string _empAcc_GetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d)
                {
                    return d.ImplementationEntity.empAcc;
                }
                private static void _empAcc_SetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.empAcc = v;
                }
                private static void _empAcc_OnValueChanged(global::LightSwitchApplication.employeecodeItem e)
                {
                    e.empAcc_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, global::System.Nullable<short>>.Entry
                    empsellStoreID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, global::System.Nullable<short>>.Entry(
                        "empsellStoreID",
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empsellStoreID_Stub,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empsellStoreID_ComputeIsReadOnly,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empsellStoreID_Validate,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empsellStoreID_GetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empsellStoreID_SetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empsellStoreID_OnValueChanged);
                private static void _empsellStoreID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.employeecodeItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, global::System.Nullable<short>>.Data> c, global::LightSwitchApplication.employeecodeItem.DetailsClass d, object sf)
                {
                    c(d, ref d._empsellStoreID, sf);
                }
                private static bool _empsellStoreID_ComputeIsReadOnly(global::LightSwitchApplication.employeecodeItem e)
                {
                    bool result = false;
                    e.empsellStoreID_IsReadOnly(ref result);
                    return result;
                }
                private static void _empsellStoreID_Validate(global::LightSwitchApplication.employeecodeItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.empsellStoreID_Validate(r);
                }
                private static global::System.Nullable<short> _empsellStoreID_GetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d)
                {
                    return d.ImplementationEntity.empsellStoreID;
                }
                private static void _empsellStoreID_SetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d, global::System.Nullable<short> v)
                {
                    d.ImplementationEntity.empsellStoreID = v;
                }
                private static void _empsellStoreID_OnValueChanged(global::LightSwitchApplication.employeecodeItem e)
                {
                    e.empsellStoreID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Entry
                    empCode = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Entry(
                        "empCode",
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empCode_Stub,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empCode_ComputeIsReadOnly,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empCode_Validate,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empCode_GetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empCode_SetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empCode_OnValueChanged);
                private static void _empCode_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.employeecodeItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.employeecodeItem.DetailsClass d, object sf)
                {
                    c(d, ref d._empCode, sf);
                }
                private static bool _empCode_ComputeIsReadOnly(global::LightSwitchApplication.employeecodeItem e)
                {
                    bool result = false;
                    e.empCode_IsReadOnly(ref result);
                    return result;
                }
                private static void _empCode_Validate(global::LightSwitchApplication.employeecodeItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.empCode_Validate(r);
                }
                private static string _empCode_GetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d)
                {
                    return d.ImplementationEntity.empCode;
                }
                private static void _empCode_SetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.empCode = v;
                }
                private static void _empCode_OnValueChanged(global::LightSwitchApplication.employeecodeItem e)
                {
                    e.empCode_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Entry
                    empPws = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Entry(
                        "empPws",
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empPws_Stub,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empPws_ComputeIsReadOnly,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empPws_Validate,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empPws_GetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empPws_SetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empPws_OnValueChanged);
                private static void _empPws_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.employeecodeItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.employeecodeItem.DetailsClass d, object sf)
                {
                    c(d, ref d._empPws, sf);
                }
                private static bool _empPws_ComputeIsReadOnly(global::LightSwitchApplication.employeecodeItem e)
                {
                    bool result = false;
                    e.empPws_IsReadOnly(ref result);
                    return result;
                }
                private static void _empPws_Validate(global::LightSwitchApplication.employeecodeItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.empPws_Validate(r);
                }
                private static string _empPws_GetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d)
                {
                    return d.ImplementationEntity.empPws;
                }
                private static void _empPws_SetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.empPws = v;
                }
                private static void _empPws_OnValueChanged(global::LightSwitchApplication.employeecodeItem e)
                {
                    e.empPws_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Entry
                    empName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Entry(
                        "empName",
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empName_Stub,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empName_ComputeIsReadOnly,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empName_Validate,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empName_GetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empName_SetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empName_OnValueChanged);
                private static void _empName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.employeecodeItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.employeecodeItem.DetailsClass d, object sf)
                {
                    c(d, ref d._empName, sf);
                }
                private static bool _empName_ComputeIsReadOnly(global::LightSwitchApplication.employeecodeItem e)
                {
                    bool result = false;
                    e.empName_IsReadOnly(ref result);
                    return result;
                }
                private static void _empName_Validate(global::LightSwitchApplication.employeecodeItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.empName_Validate(r);
                }
                private static string _empName_GetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d)
                {
                    return d.ImplementationEntity.empName;
                }
                private static void _empName_SetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.empName = v;
                }
                private static void _empName_OnValueChanged(global::LightSwitchApplication.employeecodeItem e)
                {
                    e.empName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Entry
                    empTel = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Entry(
                        "empTel",
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empTel_Stub,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empTel_ComputeIsReadOnly,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empTel_Validate,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empTel_GetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empTel_SetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empTel_OnValueChanged);
                private static void _empTel_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.employeecodeItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.employeecodeItem.DetailsClass d, object sf)
                {
                    c(d, ref d._empTel, sf);
                }
                private static bool _empTel_ComputeIsReadOnly(global::LightSwitchApplication.employeecodeItem e)
                {
                    bool result = false;
                    e.empTel_IsReadOnly(ref result);
                    return result;
                }
                private static void _empTel_Validate(global::LightSwitchApplication.employeecodeItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.empTel_Validate(r);
                }
                private static string _empTel_GetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d)
                {
                    return d.ImplementationEntity.empTel;
                }
                private static void _empTel_SetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.empTel = v;
                }
                private static void _empTel_OnValueChanged(global::LightSwitchApplication.employeecodeItem e)
                {
                    e.empTel_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Entry
                    empMobile = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Entry(
                        "empMobile",
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empMobile_Stub,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empMobile_ComputeIsReadOnly,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empMobile_Validate,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empMobile_GetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empMobile_SetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empMobile_OnValueChanged);
                private static void _empMobile_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.employeecodeItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.employeecodeItem.DetailsClass d, object sf)
                {
                    c(d, ref d._empMobile, sf);
                }
                private static bool _empMobile_ComputeIsReadOnly(global::LightSwitchApplication.employeecodeItem e)
                {
                    bool result = false;
                    e.empMobile_IsReadOnly(ref result);
                    return result;
                }
                private static void _empMobile_Validate(global::LightSwitchApplication.employeecodeItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.empMobile_Validate(r);
                }
                private static string _empMobile_GetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d)
                {
                    return d.ImplementationEntity.empMobile;
                }
                private static void _empMobile_SetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.empMobile = v;
                }
                private static void _empMobile_OnValueChanged(global::LightSwitchApplication.employeecodeItem e)
                {
                    e.empMobile_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Entry
                    empAdd = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Entry(
                        "empAdd",
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empAdd_Stub,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empAdd_ComputeIsReadOnly,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empAdd_Validate,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empAdd_GetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empAdd_SetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empAdd_OnValueChanged);
                private static void _empAdd_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.employeecodeItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.employeecodeItem.DetailsClass d, object sf)
                {
                    c(d, ref d._empAdd, sf);
                }
                private static bool _empAdd_ComputeIsReadOnly(global::LightSwitchApplication.employeecodeItem e)
                {
                    bool result = false;
                    e.empAdd_IsReadOnly(ref result);
                    return result;
                }
                private static void _empAdd_Validate(global::LightSwitchApplication.employeecodeItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.empAdd_Validate(r);
                }
                private static string _empAdd_GetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d)
                {
                    return d.ImplementationEntity.empAdd;
                }
                private static void _empAdd_SetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.empAdd = v;
                }
                private static void _empAdd_OnValueChanged(global::LightSwitchApplication.employeecodeItem e)
                {
                    e.empAdd_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, global::System.Nullable<short>>.Entry
                    empDepar = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, global::System.Nullable<short>>.Entry(
                        "empDepar",
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empDepar_Stub,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empDepar_ComputeIsReadOnly,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empDepar_Validate,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empDepar_GetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empDepar_SetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empDepar_OnValueChanged);
                private static void _empDepar_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.employeecodeItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, global::System.Nullable<short>>.Data> c, global::LightSwitchApplication.employeecodeItem.DetailsClass d, object sf)
                {
                    c(d, ref d._empDepar, sf);
                }
                private static bool _empDepar_ComputeIsReadOnly(global::LightSwitchApplication.employeecodeItem e)
                {
                    bool result = false;
                    e.empDepar_IsReadOnly(ref result);
                    return result;
                }
                private static void _empDepar_Validate(global::LightSwitchApplication.employeecodeItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.empDepar_Validate(r);
                }
                private static global::System.Nullable<short> _empDepar_GetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d)
                {
                    return d.ImplementationEntity.empDepar;
                }
                private static void _empDepar_SetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d, global::System.Nullable<short> v)
                {
                    d.ImplementationEntity.empDepar = v;
                }
                private static void _empDepar_OnValueChanged(global::LightSwitchApplication.employeecodeItem e)
                {
                    e.empDepar_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Entry
                    isAdmin = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Entry(
                        "isAdmin",
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._isAdmin_Stub,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._isAdmin_ComputeIsReadOnly,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._isAdmin_Validate,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._isAdmin_GetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._isAdmin_SetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._isAdmin_OnValueChanged);
                private static void _isAdmin_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.employeecodeItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.employeecodeItem.DetailsClass d, object sf)
                {
                    c(d, ref d._isAdmin, sf);
                }
                private static bool _isAdmin_ComputeIsReadOnly(global::LightSwitchApplication.employeecodeItem e)
                {
                    bool result = false;
                    e.isAdmin_IsReadOnly(ref result);
                    return result;
                }
                private static void _isAdmin_Validate(global::LightSwitchApplication.employeecodeItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.isAdmin_Validate(r);
                }
                private static string _isAdmin_GetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d)
                {
                    return d.ImplementationEntity.isAdmin;
                }
                private static void _isAdmin_SetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.isAdmin = v;
                }
                private static void _isAdmin_OnValueChanged(global::LightSwitchApplication.employeecodeItem e)
                {
                    e.isAdmin_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Entry
                    empEmail = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Entry(
                        "empEmail",
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empEmail_Stub,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empEmail_ComputeIsReadOnly,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empEmail_Validate,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empEmail_GetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empEmail_SetImplementationValue,
                        global::LightSwitchApplication.employeecodeItem.DetailsClass.PropertySetProperties._empEmail_OnValueChanged);
                private static void _empEmail_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.employeecodeItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.employeecodeItem.DetailsClass d, object sf)
                {
                    c(d, ref d._empEmail, sf);
                }
                private static bool _empEmail_ComputeIsReadOnly(global::LightSwitchApplication.employeecodeItem e)
                {
                    bool result = false;
                    e.empEmail_IsReadOnly(ref result);
                    return result;
                }
                private static void _empEmail_Validate(global::LightSwitchApplication.employeecodeItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.empEmail_Validate(r);
                }
                private static string _empEmail_GetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d)
                {
                    return d.ImplementationEntity.empEmail;
                }
                private static void _empEmail_SetImplementationValue(global::LightSwitchApplication.employeecodeItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.empEmail = v;
                }
                private static void _empEmail_OnValueChanged(global::LightSwitchApplication.employeecodeItem e)
                {
                    e.empEmail_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, int>.Data _empID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Data _empAcc;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, global::System.Nullable<short>>.Data _empsellStoreID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Data _empCode;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Data _empPws;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Data _empName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Data _empTel;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Data _empMobile;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Data _empAdd;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, global::System.Nullable<short>>.Data _empDepar;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Data _isAdmin;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.employeecodeItem, global::LightSwitchApplication.employeecodeItem.DetailsClass, string>.Data _empEmail;
            
        }
    
        #endregion
    }
    
    #endregion
}
