

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// 沒有可用的模型化描述
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class eorderstatuscodeItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.eorderstatuscodeItem, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// 初始化 eorderstatuscodeItem 實體的新執行個體。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public eorderstatuscodeItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public eorderstatuscodeItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.eorderstatuscodeItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void eorderstatuscodeItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void eorderstatuscodeItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// 取得這個應用程式的 Application 物件。Application 物件提供對現用螢幕的存取、開啟螢幕的方法，以及對目前使用者的存取。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// 取得包含資料工作區。資料工作區提供對應用程式中所有資料來源的存取。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int eStatusID
        {
            get
            {
                return global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.GetValue(this, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.PropertySetProperties.eStatusID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void eStatusID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void eStatusID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void eStatusID_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string esDesc
        {
            get
            {
                return global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.GetValue(this, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.PropertySetProperties.esDesc);
            }
            set
            {
                global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.SetValue(this, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.PropertySetProperties.esDesc, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void esDesc_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void esDesc_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void esDesc_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.eorderstatuscodeItem,
                global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass,
                global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.eorderstatuscodeItem, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.eorderstatuscodeItem, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.PropertySetProperties.eStatusID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.eorderstatuscodeItem, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass>.Entry
                __eorderstatuscodeItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.eorderstatuscodeItem, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.__eorderstatuscodeItem_CreateNew,
                    global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.__eorderstatuscodeItem_Created,
                    global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.__eorderstatuscodeItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.eorderstatuscodeItem __eorderstatuscodeItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.eorderstatuscodeItem> es)
            {
                return new global::LightSwitchApplication.eorderstatuscodeItem(es);
            }
            private static void __eorderstatuscodeItem_Created(global::LightSwitchApplication.eorderstatuscodeItem e)
            {
                e.eorderstatuscodeItem_Created();
            }
            private static bool __eorderstatuscodeItem_AllowSaveWithErrors(global::LightSwitchApplication.eorderstatuscodeItem e)
            {
                bool result = false;
                e.eorderstatuscodeItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.eorderstatuscodeItem, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.eorderstatuscodeItem, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.eorderstatuscodeItem, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderstatuscodeItem, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass, int> eStatusID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.PropertySetProperties.eStatusID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderstatuscodeItem, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderstatuscodeItem, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass, string> esDesc
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.PropertySetProperties.esDesc) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderstatuscodeItem, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int eStatusID { get; }
                new string esDesc { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderstatuscodeItem, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass, int>.Entry
                    eStatusID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderstatuscodeItem, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass, int>.Entry(
                        "eStatusID",
                        global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.PropertySetProperties._eStatusID_Stub,
                        global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.PropertySetProperties._eStatusID_ComputeIsReadOnly,
                        global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.PropertySetProperties._eStatusID_Validate,
                        global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.PropertySetProperties._eStatusID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.PropertySetProperties._eStatusID_OnValueChanged);
                private static void _eStatusID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderstatuscodeItem, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass d, object sf)
                {
                    c(d, ref d._eStatusID, sf);
                }
                private static bool _eStatusID_ComputeIsReadOnly(global::LightSwitchApplication.eorderstatuscodeItem e)
                {
                    bool result = false;
                    e.eStatusID_IsReadOnly(ref result);
                    return result;
                }
                private static void _eStatusID_Validate(global::LightSwitchApplication.eorderstatuscodeItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.eStatusID_Validate(r);
                }
                private static int _eStatusID_GetImplementationValue(global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass d)
                {
                    return d.ImplementationEntity.eStatusID;
                }
                private static void _eStatusID_OnValueChanged(global::LightSwitchApplication.eorderstatuscodeItem e)
                {
                    e.eStatusID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderstatuscodeItem, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass, string>.Entry
                    esDesc = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderstatuscodeItem, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass, string>.Entry(
                        "esDesc",
                        global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.PropertySetProperties._esDesc_Stub,
                        global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.PropertySetProperties._esDesc_ComputeIsReadOnly,
                        global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.PropertySetProperties._esDesc_Validate,
                        global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.PropertySetProperties._esDesc_GetImplementationValue,
                        global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.PropertySetProperties._esDesc_SetImplementationValue,
                        global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.PropertySetProperties._esDesc_OnValueChanged);
                private static void _esDesc_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderstatuscodeItem, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass d, object sf)
                {
                    c(d, ref d._esDesc, sf);
                }
                private static bool _esDesc_ComputeIsReadOnly(global::LightSwitchApplication.eorderstatuscodeItem e)
                {
                    bool result = false;
                    e.esDesc_IsReadOnly(ref result);
                    return result;
                }
                private static void _esDesc_Validate(global::LightSwitchApplication.eorderstatuscodeItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.esDesc_Validate(r);
                }
                private static string _esDesc_GetImplementationValue(global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass d)
                {
                    return d.ImplementationEntity.esDesc;
                }
                private static void _esDesc_SetImplementationValue(global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.esDesc = v;
                }
                private static void _esDesc_OnValueChanged(global::LightSwitchApplication.eorderstatuscodeItem e)
                {
                    e.esDesc_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderstatuscodeItem, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass, int>.Data _eStatusID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.eorderstatuscodeItem, global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass, string>.Data _esDesc;
            
        }
    
        #endregion
    }
    
    #endregion
}
