

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// 沒有可用的模型化描述
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class paywaycodeItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// 初始化 paywaycodeItem 實體的新執行個體。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public paywaycodeItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public paywaycodeItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.paywaycodeItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.paywaycodeItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void paywaycodeItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void paywaycodeItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// 取得這個應用程式的 Application 物件。Application 物件提供對現用螢幕的存取、開啟螢幕的方法，以及對目前使用者的存取。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// 取得包含資料工作區。資料工作區提供對應用程式中所有資料來源的存取。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public short payID
        {
            get
            {
                return global::LightSwitchApplication.paywaycodeItem.DetailsClass.GetValue(this, global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties.payID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void payID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void payID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void payID_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string payDesc
        {
            get
            {
                return global::LightSwitchApplication.paywaycodeItem.DetailsClass.GetValue(this, global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties.payDesc);
            }
            set
            {
                global::LightSwitchApplication.paywaycodeItem.DetailsClass.SetValue(this, global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties.payDesc, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void payDesc_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void payDesc_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void payDesc_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.suppliercodeItem> suppliercode
        {
            get
            {
                return global::LightSwitchApplication.paywaycodeItem.DetailsClass.GetValue(this, global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties.suppliercode);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.suppliercodeItem> suppliercodeQuery
        {
            get
            {
                return global::LightSwitchApplication.paywaycodeItem.DetailsClass.GetQuery(this, global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties.suppliercode);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.paywaycodeItem,
                global::LightSwitchApplication.paywaycodeItem.DetailsClass,
                global::LightSwitchApplication.paywaycodeItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties.payID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass>.Entry
                __paywaycodeItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.paywaycodeItem.DetailsClass.__paywaycodeItem_CreateNew,
                    global::LightSwitchApplication.paywaycodeItem.DetailsClass.__paywaycodeItem_Created,
                    global::LightSwitchApplication.paywaycodeItem.DetailsClass.__paywaycodeItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.paywaycodeItem __paywaycodeItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.paywaycodeItem> es)
            {
                return new global::LightSwitchApplication.paywaycodeItem(es);
            }
            private static void __paywaycodeItem_Created(global::LightSwitchApplication.paywaycodeItem e)
            {
                e.paywaycodeItem_Created();
            }
            private static bool __paywaycodeItem_AllowSaveWithErrors(global::LightSwitchApplication.paywaycodeItem e)
            {
                bool result = false;
                e.paywaycodeItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass, short> payID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties.payID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass, short>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass, string> payDesc
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties.payDesc) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass, global::LightSwitchApplication.suppliercodeItem> suppliercode
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties.suppliercode) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass, global::LightSwitchApplication.suppliercodeItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new short payID { get; }
                new string payDesc { get; set; }
                new global::System.Collections.IEnumerable suppliercode { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass, short>.Entry
                    payID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass, short>.Entry(
                        "payID",
                        global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties._payID_Stub,
                        global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties._payID_ComputeIsReadOnly,
                        global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties._payID_Validate,
                        global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties._payID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties._payID_OnValueChanged);
                private static void _payID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.paywaycodeItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass, short>.Data> c, global::LightSwitchApplication.paywaycodeItem.DetailsClass d, object sf)
                {
                    c(d, ref d._payID, sf);
                }
                private static bool _payID_ComputeIsReadOnly(global::LightSwitchApplication.paywaycodeItem e)
                {
                    bool result = false;
                    e.payID_IsReadOnly(ref result);
                    return result;
                }
                private static void _payID_Validate(global::LightSwitchApplication.paywaycodeItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.payID_Validate(r);
                }
                private static short _payID_GetImplementationValue(global::LightSwitchApplication.paywaycodeItem.DetailsClass d)
                {
                    return d.ImplementationEntity.payID;
                }
                private static void _payID_OnValueChanged(global::LightSwitchApplication.paywaycodeItem e)
                {
                    e.payID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass, string>.Entry
                    payDesc = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass, string>.Entry(
                        "payDesc",
                        global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties._payDesc_Stub,
                        global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties._payDesc_ComputeIsReadOnly,
                        global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties._payDesc_Validate,
                        global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties._payDesc_GetImplementationValue,
                        global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties._payDesc_SetImplementationValue,
                        global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties._payDesc_OnValueChanged);
                private static void _payDesc_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.paywaycodeItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.paywaycodeItem.DetailsClass d, object sf)
                {
                    c(d, ref d._payDesc, sf);
                }
                private static bool _payDesc_ComputeIsReadOnly(global::LightSwitchApplication.paywaycodeItem e)
                {
                    bool result = false;
                    e.payDesc_IsReadOnly(ref result);
                    return result;
                }
                private static void _payDesc_Validate(global::LightSwitchApplication.paywaycodeItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.payDesc_Validate(r);
                }
                private static string _payDesc_GetImplementationValue(global::LightSwitchApplication.paywaycodeItem.DetailsClass d)
                {
                    return d.ImplementationEntity.payDesc;
                }
                private static void _payDesc_SetImplementationValue(global::LightSwitchApplication.paywaycodeItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.payDesc = v;
                }
                private static void _payDesc_OnValueChanged(global::LightSwitchApplication.paywaycodeItem e)
                {
                    e.payDesc_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass, global::LightSwitchApplication.suppliercodeItem>.Entry
                    suppliercode = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass, global::LightSwitchApplication.suppliercodeItem>.Entry(
                        "suppliercode",
                        global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties._suppliercode_Stub,
                        global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties._suppliercode_GetReferencedEntities,
                        global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties._suppliercode_GetEntityCollection);
                private static void _suppliercode_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.paywaycodeItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass, global::LightSwitchApplication.suppliercodeItem>.Data> c, global::LightSwitchApplication.paywaycodeItem.DetailsClass d, object sf)
                {
                    c(d, ref d._suppliercode, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.suppliercodeItem> _suppliercode_GetReferencedEntities(global::LightSwitchApplication.paywaycodeItem.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.suppliercodeItem, global::LightSwitchApplication.suppliercodeItem.DetailsClass>(global::LightSwitchApplication.paywaycodeItem.DetailsClass.PropertySetProperties.suppliercode, ref d._suppliercode);
                }
                private static global::System.Collections.IEnumerable _suppliercode_GetEntityCollection(global::LightSwitchApplication.paywaycodeItem.DetailsClass d)
                {
                    return d.ImplementationEntity.suppliercode;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass, short>.Data _payID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass, string>.Data _payDesc;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.paywaycodeItem, global::LightSwitchApplication.paywaycodeItem.DetailsClass, global::LightSwitchApplication.suppliercodeItem>.Data _suppliercode;
            
        }
    
        #endregion
    }
    
    #endregion
}
