

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// 沒有可用的模型化描述
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class sendtypeItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// 初始化 sendtypeItem 實體的新執行個體。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sendtypeItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sendtypeItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.sendtypeItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.sendtypeItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendtypeItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendtypeItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// 取得這個應用程式的 Application 物件。Application 物件提供對現用螢幕的存取、開啟螢幕的方法，以及對目前使用者的存取。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// 取得包含資料工作區。資料工作區提供對應用程式中所有資料來源的存取。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public short sendTypeID
        {
            get
            {
                return global::LightSwitchApplication.sendtypeItem.DetailsClass.GetValue(this, global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties.sendTypeID);
            }
            set
            {
                global::LightSwitchApplication.sendtypeItem.DetailsClass.SetValue(this, global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties.sendTypeID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendTypeID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendTypeID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendTypeID_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string sendTypeName
        {
            get
            {
                return global::LightSwitchApplication.sendtypeItem.DetailsClass.GetValue(this, global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties.sendTypeName);
            }
            set
            {
                global::LightSwitchApplication.sendtypeItem.DetailsClass.SetValue(this, global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties.sendTypeName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendTypeName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendTypeName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sendTypeName_Changed();

        /// <summary>
        /// 沒有可用的模型化描述
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.sendrecordItem> sendrecord
        {
            get
            {
                return global::LightSwitchApplication.sendtypeItem.DetailsClass.GetValue(this, global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties.sendrecord);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.sendrecordItem> sendrecordQuery
        {
            get
            {
                return global::LightSwitchApplication.sendtypeItem.DetailsClass.GetQuery(this, global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties.sendrecord);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.sendtypeItem,
                global::LightSwitchApplication.sendtypeItem.DetailsClass,
                global::LightSwitchApplication.sendtypeItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties.sendTypeID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass>.Entry
                __sendtypeItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.sendtypeItem.DetailsClass.__sendtypeItem_CreateNew,
                    global::LightSwitchApplication.sendtypeItem.DetailsClass.__sendtypeItem_Created,
                    global::LightSwitchApplication.sendtypeItem.DetailsClass.__sendtypeItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.sendtypeItem __sendtypeItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.sendtypeItem> es)
            {
                return new global::LightSwitchApplication.sendtypeItem(es);
            }
            private static void __sendtypeItem_Created(global::LightSwitchApplication.sendtypeItem e)
            {
                e.sendtypeItem_Created();
            }
            private static bool __sendtypeItem_AllowSaveWithErrors(global::LightSwitchApplication.sendtypeItem e)
            {
                bool result = false;
                e.sendtypeItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass, short> sendTypeID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties.sendTypeID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass, short>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass, string> sendTypeName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties.sendTypeName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass, global::LightSwitchApplication.sendrecordItem> sendrecord
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties.sendrecord) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass, global::LightSwitchApplication.sendrecordItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new short sendTypeID { get; set; }
                new string sendTypeName { get; set; }
                new global::System.Collections.IEnumerable sendrecord { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass, short>.Entry
                    sendTypeID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass, short>.Entry(
                        "sendTypeID",
                        global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties._sendTypeID_Stub,
                        global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties._sendTypeID_ComputeIsReadOnly,
                        global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties._sendTypeID_Validate,
                        global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties._sendTypeID_GetImplementationValue,
                        global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties._sendTypeID_SetImplementationValue,
                        global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties._sendTypeID_OnValueChanged);
                private static void _sendTypeID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.sendtypeItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass, short>.Data> c, global::LightSwitchApplication.sendtypeItem.DetailsClass d, object sf)
                {
                    c(d, ref d._sendTypeID, sf);
                }
                private static bool _sendTypeID_ComputeIsReadOnly(global::LightSwitchApplication.sendtypeItem e)
                {
                    bool result = false;
                    e.sendTypeID_IsReadOnly(ref result);
                    return result;
                }
                private static void _sendTypeID_Validate(global::LightSwitchApplication.sendtypeItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.sendTypeID_Validate(r);
                }
                private static short _sendTypeID_GetImplementationValue(global::LightSwitchApplication.sendtypeItem.DetailsClass d)
                {
                    return d.ImplementationEntity.sendTypeID;
                }
                private static void _sendTypeID_SetImplementationValue(global::LightSwitchApplication.sendtypeItem.DetailsClass d, short v)
                {
                    d.ImplementationEntity.sendTypeID = v;
                }
                private static void _sendTypeID_OnValueChanged(global::LightSwitchApplication.sendtypeItem e)
                {
                    e.sendTypeID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass, string>.Entry
                    sendTypeName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass, string>.Entry(
                        "sendTypeName",
                        global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties._sendTypeName_Stub,
                        global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties._sendTypeName_ComputeIsReadOnly,
                        global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties._sendTypeName_Validate,
                        global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties._sendTypeName_GetImplementationValue,
                        global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties._sendTypeName_SetImplementationValue,
                        global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties._sendTypeName_OnValueChanged);
                private static void _sendTypeName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.sendtypeItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.sendtypeItem.DetailsClass d, object sf)
                {
                    c(d, ref d._sendTypeName, sf);
                }
                private static bool _sendTypeName_ComputeIsReadOnly(global::LightSwitchApplication.sendtypeItem e)
                {
                    bool result = false;
                    e.sendTypeName_IsReadOnly(ref result);
                    return result;
                }
                private static void _sendTypeName_Validate(global::LightSwitchApplication.sendtypeItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.sendTypeName_Validate(r);
                }
                private static string _sendTypeName_GetImplementationValue(global::LightSwitchApplication.sendtypeItem.DetailsClass d)
                {
                    return d.ImplementationEntity.sendTypeName;
                }
                private static void _sendTypeName_SetImplementationValue(global::LightSwitchApplication.sendtypeItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.sendTypeName = v;
                }
                private static void _sendTypeName_OnValueChanged(global::LightSwitchApplication.sendtypeItem e)
                {
                    e.sendTypeName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass, global::LightSwitchApplication.sendrecordItem>.Entry
                    sendrecord = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass, global::LightSwitchApplication.sendrecordItem>.Entry(
                        "sendrecord",
                        global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties._sendrecord_Stub,
                        global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties._sendrecord_GetReferencedEntities,
                        global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties._sendrecord_GetEntityCollection);
                private static void _sendrecord_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.sendtypeItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass, global::LightSwitchApplication.sendrecordItem>.Data> c, global::LightSwitchApplication.sendtypeItem.DetailsClass d, object sf)
                {
                    c(d, ref d._sendrecord, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.sendrecordItem> _sendrecord_GetReferencedEntities(global::LightSwitchApplication.sendtypeItem.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.sendrecordItem, global::LightSwitchApplication.sendrecordItem.DetailsClass>(global::LightSwitchApplication.sendtypeItem.DetailsClass.PropertySetProperties.sendrecord, ref d._sendrecord);
                }
                private static global::System.Collections.IEnumerable _sendrecord_GetEntityCollection(global::LightSwitchApplication.sendtypeItem.DetailsClass d)
                {
                    return d.ImplementationEntity.sendrecord;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass, short>.Data _sendTypeID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass, string>.Data _sendTypeName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.sendtypeItem, global::LightSwitchApplication.sendtypeItem.DetailsClass, global::LightSwitchApplication.sendrecordItem>.Data _sendrecord;
            
        }
    
        #endregion
    }
    
    #endregion
}
