//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class inikierpDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::inikierpData.Implementation.inikierpDataObjectContext>
    {
    
        public inikierpDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService()
        {
            return new global::LightSwitchApplication.DataWorkspace().inikierpData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class inikierpDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::inikierpData.Implementation.inikierpDataObjectContext>
    {
        public inikierpDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
        public global::System.Linq.IQueryable<global::inikierpData.Implementation.customercodeItem> CustomerQuery(string companyName, string contactName, string simpleComany, global::System.Nullable<short> cusKind)
        {
            global::System.Linq.IQueryable<global::inikierpData.Implementation.customercodeItem> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::inikierpData.Implementation.customercodeItem>("customercode"),
                (c) => (((((companyName == null) || (c.companyName.CompareTo(companyName) == 0)) && ((contactName == null) || (c.contactName.CompareTo(contactName) == 0))) && ((simpleComany == null) || (c.simpleComany.CompareTo(simpleComany) == 0))) && ((cusKind.HasValue == false) || (c.cusKind.HasValue && (cusKind.HasValue && (c.cusKind == cusKind))))));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::inikierpData.Implementation.sendrecordItem> SendRecordQuery(string sendTypeName, global::System.Nullable<global::System.DateTime> sendDate)
        {
            global::System.Linq.IQueryable<global::inikierpData.Implementation.sendrecordItem> query;
            query = global::System.Linq.Queryable.OrderByDescending(
                global::System.Linq.Queryable.Where(
                    this.GetQuery<global::inikierpData.Implementation.sendrecordItem>("sendrecord"),
                    (s) => (((sendTypeName == null) || (s.sendtypeItem.sendTypeName.CompareTo(sendTypeName) == 0)) && ((sendDate.HasValue == false) || (s.sendDate.HasValue && (sendDate.HasValue && (s.sendDate == sendDate)))))),
                (s) => s.sendDate);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::inikierpData.Implementation.eorderItem> EorderQuery(string companyName, string orderNo, global::System.Nullable<global::System.DateTime> eoDate, global::System.Nullable<global::System.DateTime> eoDate1, string storeNumber)
        {
            global::System.Linq.IQueryable<global::inikierpData.Implementation.eorderItem> query;
            query = global::System.Linq.Queryable.OrderByDescending(
                global::System.Linq.Queryable.Where(
                    this.GetQuery<global::inikierpData.Implementation.eorderItem>("eorder"),
                    (e) => ((((((((companyName == null) || (e.customercodeItem1.companyName.CompareTo(companyName) == 0)) && ((companyName == null) || (e.customercodeItem1.contactName.CompareTo(companyName) == 0))) && ((companyName == null) || (e.customercodeItem1.cusName.CompareTo(companyName) == 0))) && ((orderNo == null) || (e.orderNo.CompareTo(orderNo) == 0))) && ((eoDate.HasValue == false) || (e.eoDate.HasValue && (eoDate.HasValue && (e.eoDate >= eoDate))))) && ((eoDate1.HasValue == false) || (e.eoDate.HasValue && (eoDate1.HasValue && (e.eoDate <= eoDate1))))) && ((storeNumber == null) || (e.storeNumber.CompareTo(storeNumber) == 0)))),
                (e) => e.odID);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::inikierpData.Implementation.sendrecordItem> SendRecordForEorder(global::System.Nullable<long> odID)
        {
            global::System.Linq.IQueryable<global::inikierpData.Implementation.sendrecordItem> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::inikierpData.Implementation.sendrecordItem>("sendrecord"),
                (s) => ((odID.HasValue == false) || (odID.HasValue && (s.odID == odID))));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::inikierpData.Implementation.invtitlecodeItem> invtitlecodeForEorder(global::System.Nullable<long> cusID, global::System.Nullable<int> invTitleCode)
        {
            global::System.Linq.IQueryable<global::inikierpData.Implementation.invtitlecodeItem> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::inikierpData.Implementation.invtitlecodeItem>("invtitlecode"),
                (i) => (((cusID.HasValue == false) || (cusID.HasValue && (i.customercodeItem1.cusID == cusID))) && ((invTitleCode.HasValue == false) || (invTitleCode.HasValue && (i.invTitleCode == invTitleCode)))));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::inikierpData.Implementation.productcodeItem> ProductCodeQuery(string prodDesc, string prodSeq, string pStorageSpaces)
        {
            global::System.Linq.IQueryable<global::inikierpData.Implementation.productcodeItem> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::inikierpData.Implementation.productcodeItem>("productcode"),
                (p) => ((((prodDesc == null) || p.prodDesc.Contains(prodDesc)) && ((prodSeq == null) || p.prodSeq.Contains(prodSeq))) && ((pStorageSpaces == null) || p.pStorageSpaces.Contains(pStorageSpaces))));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::inikierpData.Implementation.suppliercodeItem> SupplierCodeQuery(string supName, string supTax)
        {
            global::System.Linq.IQueryable<global::inikierpData.Implementation.suppliercodeItem> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::inikierpData.Implementation.suppliercodeItem>("suppliercode"),
                (s) => (((supName == null) || s.supName.Contains(supName)) && ((supTax == null) || (s.supTax.CompareTo(supTax) == 0))));
            return query;
        }
    
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::inikierpData.Implementation.cuskindcodeItem))
            {
                return new global::inikierpData.Implementation.cuskindcodeItem();
            }
            if (type == typeof(global::inikierpData.Implementation.customercodeItem))
            {
                return new global::inikierpData.Implementation.customercodeItem();
            }
            if (type == typeof(global::inikierpData.Implementation.sendrecordItem))
            {
                return new global::inikierpData.Implementation.sendrecordItem();
            }
            if (type == typeof(global::inikierpData.Implementation.eorderItem))
            {
                return new global::inikierpData.Implementation.eorderItem();
            }
            if (type == typeof(global::inikierpData.Implementation.sendtypeItem))
            {
                return new global::inikierpData.Implementation.sendtypeItem();
            }
            if (type == typeof(global::inikierpData.Implementation.eorderitemItem))
            {
                return new global::inikierpData.Implementation.eorderitemItem();
            }
            if (type == typeof(global::inikierpData.Implementation.eorderstatuscodeItem))
            {
                return new global::inikierpData.Implementation.eorderstatuscodeItem();
            }
            if (type == typeof(global::inikierpData.Implementation.productclassItem))
            {
                return new global::inikierpData.Implementation.productclassItem();
            }
            if (type == typeof(global::inikierpData.Implementation.productcodeItem))
            {
                return new global::inikierpData.Implementation.productcodeItem();
            }
            if (type == typeof(global::inikierpData.Implementation.employeecodeItem))
            {
                return new global::inikierpData.Implementation.employeecodeItem();
            }
            if (type == typeof(global::inikierpData.Implementation.invtitlecodeItem))
            {
                return new global::inikierpData.Implementation.invtitlecodeItem();
            }
            if (type == typeof(global::inikierpData.Implementation.unitcodeItem))
            {
                return new global::inikierpData.Implementation.unitcodeItem();
            }
            if (type == typeof(global::inikierpData.Implementation.punitcodeItem))
            {
                return new global::inikierpData.Implementation.punitcodeItem();
            }
            if (type == typeof(global::inikierpData.Implementation.suppliercodeItem))
            {
                return new global::inikierpData.Implementation.suppliercodeItem();
            }
            if (type == typeof(global::inikierpData.Implementation.paywaycodeItem))
            {
                return new global::inikierpData.Implementation.paywaycodeItem();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::inikierpData.Implementation.inikierpDataObjectContext CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::inikierpData.Implementation.inikierpDataObjectContext(base.GetEntityConnectionString(
                "inikierpData", 
                "res://" + assemblyName + "/inikierpData.csdl|res://" + assemblyName + "/inikierpData.ssdl|res://" + assemblyName + "/inikierpData.msl", 
                "System.Data.SqlClient"));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.cuskindcodeItem))
            {
                return new global::inikierpData.Implementation.cuskindcodeItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.customercodeItem))
            {
                return new global::inikierpData.Implementation.customercodeItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.sendrecordItem))
            {
                return new global::inikierpData.Implementation.sendrecordItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.eorderItem))
            {
                return new global::inikierpData.Implementation.eorderItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.sendtypeItem))
            {
                return new global::inikierpData.Implementation.sendtypeItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.eorderitemItem))
            {
                return new global::inikierpData.Implementation.eorderitemItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.eorderstatuscodeItem))
            {
                return new global::inikierpData.Implementation.eorderstatuscodeItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.productclassItem))
            {
                return new global::inikierpData.Implementation.productclassItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.productcodeItem))
            {
                return new global::inikierpData.Implementation.productcodeItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.employeecodeItem))
            {
                return new global::inikierpData.Implementation.employeecodeItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.invtitlecodeItem))
            {
                return new global::inikierpData.Implementation.invtitlecodeItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.unitcodeItem))
            {
                return new global::inikierpData.Implementation.unitcodeItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.punitcodeItem))
            {
                return new global::inikierpData.Implementation.punitcodeItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.suppliercodeItem))
            {
                return new global::inikierpData.Implementation.suppliercodeItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.paywaycodeItem))
            {
                return new global::inikierpData.Implementation.paywaycodeItem();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.inikierpData))
            {
                return new global::LightSwitchApplication.inikierpDataService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.inikierpData))
            {
                return new global::LightSwitchApplication.Implementation.inikierpDataServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.cuskindcodeItem) == definitionType)
            {
                return typeof(global::inikierpData.Implementation.cuskindcodeItem);
            }
            if (typeof(global::LightSwitchApplication.customercodeItem) == definitionType)
            {
                return typeof(global::inikierpData.Implementation.customercodeItem);
            }
            if (typeof(global::LightSwitchApplication.sendrecordItem) == definitionType)
            {
                return typeof(global::inikierpData.Implementation.sendrecordItem);
            }
            if (typeof(global::LightSwitchApplication.eorderItem) == definitionType)
            {
                return typeof(global::inikierpData.Implementation.eorderItem);
            }
            if (typeof(global::LightSwitchApplication.sendtypeItem) == definitionType)
            {
                return typeof(global::inikierpData.Implementation.sendtypeItem);
            }
            if (typeof(global::LightSwitchApplication.eorderitemItem) == definitionType)
            {
                return typeof(global::inikierpData.Implementation.eorderitemItem);
            }
            if (typeof(global::LightSwitchApplication.eorderstatuscodeItem) == definitionType)
            {
                return typeof(global::inikierpData.Implementation.eorderstatuscodeItem);
            }
            if (typeof(global::LightSwitchApplication.productclassItem) == definitionType)
            {
                return typeof(global::inikierpData.Implementation.productclassItem);
            }
            if (typeof(global::LightSwitchApplication.productcodeItem) == definitionType)
            {
                return typeof(global::inikierpData.Implementation.productcodeItem);
            }
            if (typeof(global::LightSwitchApplication.employeecodeItem) == definitionType)
            {
                return typeof(global::inikierpData.Implementation.employeecodeItem);
            }
            if (typeof(global::LightSwitchApplication.invtitlecodeItem) == definitionType)
            {
                return typeof(global::inikierpData.Implementation.invtitlecodeItem);
            }
            if (typeof(global::LightSwitchApplication.unitcodeItem) == definitionType)
            {
                return typeof(global::inikierpData.Implementation.unitcodeItem);
            }
            if (typeof(global::LightSwitchApplication.punitcodeItem) == definitionType)
            {
                return typeof(global::inikierpData.Implementation.punitcodeItem);
            }
            if (typeof(global::LightSwitchApplication.suppliercodeItem) == definitionType)
            {
                return typeof(global::inikierpData.Implementation.suppliercodeItem);
            }
            if (typeof(global::LightSwitchApplication.paywaycodeItem) == definitionType)
            {
                return typeof(global::inikierpData.Implementation.paywaycodeItem);
            }
            return null;
        }
    }
}

namespace inikierpData.Implementation
{

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class cuskindcodeItem :
        global::LightSwitchApplication.cuskindcodeItem.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class customercodeItem :
        global::LightSwitchApplication.customercodeItem.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.customercodeItem.DetailsClass.IImplementation.eorder
        {
            get
            {
                return this.eorder;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.customercodeItem.DetailsClass.IImplementation.invtitlecode1
        {
            get
            {
                return this.invtitlecode1;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class sendrecordItem :
        global::LightSwitchApplication.sendrecordItem.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.sendrecordItem.DetailsClass.IImplementation.sendtypeItem
        {
            get
            {
                return this.sendtypeItem;
            }
            set
            {
                this.sendtypeItem = (global::inikierpData.Implementation.sendtypeItem)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("sendtypeItem");
                }
            }
        }
        
        partial void OnsendTypeIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("sendtypeItem");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class eorderItem :
        global::LightSwitchApplication.eorderItem.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.eorderItem.DetailsClass.IImplementation.eorderitem1
        {
            get
            {
                return this.eorderitem1;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.eorderItem.DetailsClass.IImplementation.customercodeItem1
        {
            get
            {
                return this.customercodeItem1;
            }
            set
            {
                this.customercodeItem1 = (global::inikierpData.Implementation.customercodeItem)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("customercodeItem1");
                }
            }
        }
        
        partial void OncusIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("customercodeItem1");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class sendtypeItem :
        global::LightSwitchApplication.sendtypeItem.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.sendtypeItem.DetailsClass.IImplementation.sendrecord
        {
            get
            {
                return this.sendrecord;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class eorderitemItem :
        global::LightSwitchApplication.eorderitemItem.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.eorderitemItem.DetailsClass.IImplementation.eorderItem1
        {
            get
            {
                return this.eorderItem1;
            }
            set
            {
                this.eorderItem1 = (global::inikierpData.Implementation.eorderItem)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("eorderItem1");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.eorderitemItem.DetailsClass.IImplementation.productcodeItem
        {
            get
            {
                return this.productcodeItem;
            }
            set
            {
                this.productcodeItem = (global::inikierpData.Implementation.productcodeItem)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("productcodeItem");
                }
            }
        }
        
        partial void OnodIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("eorderItem1");
            }
        }
        
        partial void OnprodIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("productcodeItem");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class eorderstatuscodeItem :
        global::LightSwitchApplication.eorderstatuscodeItem.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class productclassItem :
        global::LightSwitchApplication.productclassItem.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.productclassItem.DetailsClass.IImplementation.productcode
        {
            get
            {
                return this.productcode;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class productcodeItem :
        global::LightSwitchApplication.productcodeItem.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.productcodeItem.DetailsClass.IImplementation.eorderitem
        {
            get
            {
                return this.eorderitem;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.productcodeItem.DetailsClass.IImplementation.productclassItem
        {
            get
            {
                return this.productclassItem;
            }
            set
            {
                this.productclassItem = (global::inikierpData.Implementation.productclassItem)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("productclassItem");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.productcodeItem.DetailsClass.IImplementation.suppliercodeItem
        {
            get
            {
                return this.suppliercodeItem;
            }
            set
            {
                this.suppliercodeItem = (global::inikierpData.Implementation.suppliercodeItem)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("suppliercodeItem");
                }
            }
        }
        
        partial void OnppIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("productclassItem");
            }
        }
        
        partial void OnsupIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("suppliercodeItem");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class employeecodeItem :
        global::LightSwitchApplication.employeecodeItem.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class invtitlecodeItem :
        global::LightSwitchApplication.invtitlecodeItem.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.invtitlecodeItem.DetailsClass.IImplementation.customercodeItem1
        {
            get
            {
                return this.customercodeItem1;
            }
            set
            {
                this.customercodeItem1 = (global::inikierpData.Implementation.customercodeItem)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("customercodeItem1");
                }
            }
        }
        
        partial void OncusIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("customercodeItem1");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class unitcodeItem :
        global::LightSwitchApplication.unitcodeItem.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class punitcodeItem :
        global::LightSwitchApplication.punitcodeItem.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class suppliercodeItem :
        global::LightSwitchApplication.suppliercodeItem.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.suppliercodeItem.DetailsClass.IImplementation.productcode
        {
            get
            {
                return this.productcode;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.suppliercodeItem.DetailsClass.IImplementation.paywaycodeItem
        {
            get
            {
                return this.paywaycodeItem;
            }
            set
            {
                this.paywaycodeItem = (global::inikierpData.Implementation.paywaycodeItem)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("paywaycodeItem");
                }
            }
        }
        
        partial void OnsupPayIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("paywaycodeItem");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class paywaycodeItem :
        global::LightSwitchApplication.paywaycodeItem.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.paywaycodeItem.DetailsClass.IImplementation.suppliercode
        {
            get
            {
                return this.suppliercode;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

